src-ddd/Sample.Web/Models/ErrorViewModel.cs
using System;

namespace Sample.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src-ddd/Sample.Web/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Sample.Web.Controllers
{
    public class ChatController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src-ddd/Sample.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Sample.Web.Models;

namespace Sample.Web.Controllers
{
    public class HomeController : Controller
    {
        //private readonly IHubContext<NotificationHub>
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src-ddd/Sample.Web/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Sample.Infrastructure.Repositories;

namespace Sample.Web.Controllers
{
    public class LogController : Controller
    {
        private readonly ILogger<LogController> _logger;
        private LogRepository _logRepository;
        public LogController(ILogger<LogController> logger, LogRepository logRepository)
        {
            _logger = logger;
            _logRepository = logRepository;
        }
        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            var logs = await _logRepository.GetPaginatedList(pageNumber, 10);
            return View(logs);
        }


        public async Task<IActionResult> Details(long id)
        {
            var log = await _logRepository.GetAsync(id);
            return View(log);
        }
    }
}

src-ddd/Sample.Web/Controllers/LogRecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Sample.Infrastructure.Repositories;

namespace Sample.Web.Controllers
{
    public class LogRecordController : Controller
    {
        private readonly ILogger<LogRecordController> _logger;
        private LogRepository _logRepository;
        public LogRecordController(ILogger<LogRecordController> logger, LogRepository logRepository)
        {
            _logger = logger;
            _logRepository = logRepository;
        }
        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            var logs = await _logRepository.GetPaginatedList(pageNumber, 10);
            return View(logs);
        }


        public async Task<IActionResult> Details(long id)
        {
            var log = await _logRepository.GetAsync(id);
            return View(log);
        }
    }
}

src-ddd/Sample.Web/Controllers/RedisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Sample.Infrastructure.Cache.Redis;
using Sample.Infrastructure.Repositories;
using Newtonsoft.Json;

namespace Sample.Web.Controllers
{
    public class RedisController : Controller
    {
        RedisManager redis;
        TodoItemRepository _todoItemRepository;

        public const string strKey = "sample:test";

        public RedisController(TodoItemRepository todoItemRepository)
        {
            redis = new RedisManager();
            _todoItemRepository = todoItemRepository;
        }
        public async Task<IActionResult> Index()
        {
            var todoItems = await _todoItemRepository.GetAllAsync();
            foreach (var todo in todoItems)
            {
                await redis.SetStringAsync($"Sample:TodoItems:{todo.Id}:Datas", JsonConvert.SerializeObject(todo), TimeSpan.FromMinutes(60));
            }
            return View();
        }

        public async Task<ActionResult> GetRedisValue()
        {
            var result = await redis.GetStringAsync("Sample:TodoItems:1:Datas");
            return Json(result);
        }
    }
}

src-ddd/Sample.Web/Controllers/TodoItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Sample.Infrastructure.Repositories;

namespace Sample.Web.Controllers
{
    public class TodoItemController : Controller
    {
        private readonly ILogger<TodoItemController> _logger;
        TodoItemRepository _todoItemRepository;
        public TodoItemController(ILogger<TodoItemController> logger, TodoItemRepository todoItemRepository)
        {
            _logger = logger;
            _todoItemRepository = todoItemRepository;
        }
        public async Task<IActionResult> Index()
        {
            var todos = await _todoItemRepository.GetAllAsync();
            return View(todos);
        }
    }
}

src-ddd/Sample.Web/Controllers/TodoItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Sample.Infrastructure.Repositories;

namespace Sample.Web.Controllers
{
    public class TodoItemsController : Controller
    {
        private readonly ILogger<TodoItemsController> _logger;
        TodoItemRepository _todoItemRepository;
        public TodoItemsController(ILogger<TodoItemsController> logger, TodoItemRepository todoItemRepository)
        {
            _logger = logger;
            _todoItemRepository = todoItemRepository;
        }
        public async Task<IActionResult> Index()
        {
            var todos = await _todoItemRepository.GetAllAsync();
            return View(todos);
        }
    }
}

src-ddd/Sample.Web/Views/LogRecord/Details.cshtml
@{
    ViewData["Title"] = "Details";
}
@model Sample.Domain.Entities.Log

<h1>Details</h1>
<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th class="col-4">Key</th>
                <th class="col-8">Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>应用名称</td>
                <td>@Model.Application</td>
            </tr>
            <tr>
                <td>请求操作</td>
                <td>@Model.Action</td>
            </tr>
            <tr>
                <td>记录时间</td>
                <td>@Model.Logged</td>
            </tr>
            <tr>
                <td>请求地址</td>
                <td>@Model.Url</td>
            </tr>

            <tr>
                <td>日志等级</td>
                <td><button class="btn btn-danger">@Model.Level</button></td>
            </tr>
            <tr class="table-info">
                <td>日志信息</td>
                <td>@Model.Message</td>
            </tr>
            <tr class="table-danger">
                <td>异常信息</td>
                <td><code>@Model.Exception</code></td>
            </tr>
            <tr>
                <td>记录者</td>
                <td>@Model.Logger</td>
            </tr>
            <tr>
                <td>调用位置</td>
                <td>@Model.Callsite</td>
            </tr>
        </tbody>
    </table>
</div>

src-ddd/Sample.Web/Views/LogRecord/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model Sample.Infrastructure.Share.PaginatedList<Sample.Domain.Entities.Log>

<h1>Index</h1>

<div class="table-responsive">
    <table class="table table-hover table-striped">
        <thead class="thead-dark">
            <tr>
                <th>应用名称</th>
                <th>等级</th>
                <th>日志信息</th>
                <th>请求地址</th>
                <th>记录时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @{
                string styleTr = "";
            }
            @foreach (var item in Model)
            {
                if (item.Level.ToLower() == "error")
                {
                    styleTr = "table-danger";
                }
                else
                {
                    styleTr = "";
                }

                <tr class="@styleTr">
                    <td>
                        @item.Application
                    </td>
                    <td>
                        @item.Level
                    </td>
                    <td>
                        @item.Message
                    </td>
                    <td>
                        @item.Url
                    </td>
                    <td>
                        @item.Logged
                    </td>
                    <td>
                        <a class="btn btn-outline-primary" asp-controller="LogRecord" asp-action="Details" asp-route-id="@item.Id">查看</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        var currentPageIndex = Model.PageIndex;
    }



    <nav aria-label="...">
        <ul class="pagination justify-content-center">
            <li class="page-item @prevDisabled">
                <a asp-action="Index" asp-route-pageNumber="@(Model.PageIndex - 1)" class="page-link">
                    Previous
                </a>
            </li>

            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                if (currentPageIndex == i)
                {
                    <li class="page-item active">
                        <span class="page-link">
                            @i
                            <span class="sr-only">(current)</span>
                        </span>
                    </li>
                }
                else
                {
                    <li class="page-item"><a asp-action="Index" asp-route-pageNumber="@i" class="page-link">@i</a></li>
                }
            }

            <li class="page-item @nextDisabled">
                <a asp-action="Index" asp-route-pageNumber="@(Model.PageIndex + 1)" class="page-link ">
                    Next
                </a>
            </li>
        </ul>
    </nav>
</div>

@section Scripts{
    <script>
        $(function () {
        });
    </script>
}

src-ddd/Sample.Web/Views/TodoItem/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model List<Sample.Domain.Entities.TodoItem>

<h1>Index</h1>
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>待办事项</th>
                <th>是否完成</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @(item.IsComplete ? "是" : "否")
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>